
#用户中心服务端口
server:
  port: 8082
#数据源配置
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytwo?characterEncoding=utf-8
    username: root
    password: root
#dubbo配置
dubbo:
  application:
    name: hehe
  scan:
    # 包名根据自己的实际情况写
    base-packages: com.dabai.serviceImpl
  protocol:
    port: 20881
    name: dubbo
  registry:
    #zookeeper注册中心地址
    address: zookeeper://localhost:2181
#mybatis的相关配置
mybatis:
  #开启驼峰命名
#  configuration:
#    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml