
#用户中心服务端口
server:
  port: 8081
#数据源配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: "jdbc:mysql://localhost:3306/com.dabai.mytwo?characterEncoding=utf-8"
      username: root
      password: root
  output:
    ansi:
      enabled: always
#dubbo配置
dubbo:
  application:
    name: hehe
  scan:
    # 包名根据自己的实际情况写
    base-packages: com.dabai.serviceImpl
  protocol:
    port: 20881
    name: dubbo
  registry:
    #zookeeper注册中心地址
    address: zookeeper://127.0.0.0:2181