server:
  port: 8083

dubbo:
  application:
    name: hehe
  scan:
    base-packages: com.dabai.mytwo.controller
  registry:
    address: zookeeper://localhost:2181
  protocol:
    port: 20881
    name: dubbo
  consumer:
    timeout: 1000
    check: true
    retries: 2
  provider:
    retries: 1