server:
  port: 8044

dubbo:
  application:
    name: hehe
  scan:
    base-packages: com.dabai.mytwo.controller
  protocol:
    port: 20881
    name: dubbo
  registry:
    #zookeeper注册中心地址
    address: zookeeper://localhost:2181

spring:
  freemarker:
    template-loader-path: classpath:/static/WEB-INF/
    suffix: .html

session:
  type: 1
  url: http://10.199.140.70:8080/authorize
  client-id: wsys
  client-secret: wsysP1235
  redirect-url: http://10.199.140.70:8080
  default:
    qxswjgdm: 13100000000 # 默认权限税务机构代码
    qxswjgmc: 国家税务总局上海市税务局 # 默认权限税务机构名称