server:
  port: 8083

dubbo:
  application:
    name: hehe
  scan:
    base-packages: com.dabai.mytwo.controller
  protocol:
    port: 20881
    name: dubbo
  registry:
    #zookeeper注册中心地址
    address: zookeeper://localhost:2181